config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :demandeurs

	resources :formations do
	    collection do
	        get "liste_formations"
	    end
	end
	resources :demandes do
	    collection do
	        get "liste_demandes"
	    end
	end

	root 'demandeurs#index'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attestation.rb
class Attestation < ApplicationRecord
end

app/models/demande.rb
class Demande < ApplicationRecord
	belongs_to :demandeur
end

app/models/demandeur.rb
class Demandeur < ApplicationRecord
	has_many :demandes
	has_many :diplomes
	has_many :formations
	has_many :experiences
	has_many :langues
	has_many :stages
	has_attached_file :photo_profil, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :photo_profil, content_type: /\Aimage\/.*\z/

end

app/models/diplome.rb
class Diplome < ApplicationRecord
	belongs_to :demandeur
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/models/formation.rb
class Formation < ApplicationRecord
	belongs_to :demandeur
end

app/models/langue.rb
class Langue < ApplicationRecord
	belongs_to :demandeur
end

app/models/offre.rb
class Offre < ApplicationRecord
end

app/models/pratique.rb
class Pratique < ApplicationRecord
end

app/models/stage.rb
class Stage < ApplicationRecord
	belongs_to :demandeur
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController

	before_action :find_formation, only: [:show, :edit, :update, :destroy]
	def liste_formations
		@formations = Formation.all
	end

	def new
		@formation = Formation.new
	end

	def create
		/@formation= current_candidat.demandes.build(demande_params)/
		@formation = Formation.new(formation_params)
		if @formation.save
			redirect_to @formation
		else
			render "New"
		end
	end

	def show
		@formation=Formation.where(demandeur_id: @formation.demandeur_id).take
	end

	def edit
	end 

	def update
	end

	def destroy
	end

	private

	def formation_params
        params.require(:formation).permit(:date_df, :date_ff, :titre_formation, :institut, :demandeur_id)
    end
    
    def find_formation
        @formation= Formation.find(params[:id])
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/helpers/demandeurs_helper.rb
module DemandeursHelper
end

app/helpers/diplomes_helper.rb
module DiplomesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/langues_helper.rb
module LanguesHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/pratiques_helper.rb
module PratiquesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/formations/_form_formations_etape2.html.haml
=simple_form_for @formation do |f|
	=f.input :date_df, label: "Date début :"
	=f.input :date_ff, label: "Date fin :" 
	=f.input :titre_formation, label: "Formation" 
	=f.input :institut, label: "Institut :" 
	
	=f.button :submit

app/views/formations/liste_formations.html.haml
= link_to "Nouvelle formation", new_formation_path
%h1 les formations

#jobs

	- @formations.each do |formation|
		.job
			
				
			%p{:style=>"font-weight:bold; "}= link_to  formation.titre_formation, formation
					
			%p= "Date Début: " +formation.date_df.to_s
			%p= "Date Fin: " +formation.date_ff.to_s
			%p= "Institut: " +formation.institut.to_s

app/views/formations/new.html.haml
= link_to "Retour", root_path
%h2 Nouveau Dimplôme

=render "form_formations_etape2"

app/views/formations/show.html.haml
%h1= @formation.titre_formation
%p= "Date Début: " +@formation.date_df.to_s
%p= "Date Fin: " +@formation.date_ff.to_s
%p= "Institut: " +@formation.institut.to_s

/%p= @dem.description/
#links
 = link_to "Ajouter une nouvelle formation", "/formations/new", class: "btn btn-sm btn-default"
 = link_to "Afficher toutes les formations", "/formations/liste_formations", class: "btn btn-sm btn-default"
 /= link_to "Modifier", edit_demande_path(@demande), class: "btn btn-sm btn-default"
 //= link_to "Suprimer", demande_path(@demande), method: :delete, data: { confirm: "are you sure?" }, class: "btn btn-sm btn-default"