config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :demandeurs

	resources :formations do
	    collection do
	        get "liste_formations"
	    end
	end
	resources :demandes do
	    collection do
	        get "liste_demandes"
	    end
	end

	root 'demandeurs#index'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attestation.rb
class Attestation < ApplicationRecord
end

app/models/demande.rb
class Demande < ApplicationRecord
	belongs_to :demandeur
end

app/models/demandeur.rb
class Demandeur < ApplicationRecord
	has_many :demandes
	has_many :diplomes
	has_many :formations
	has_many :experiences
	has_many :langues
	has_many :stages
	has_attached_file :photo_profil, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :photo_profil, content_type: /\Aimage\/.*\z/

end

app/models/diplome.rb
class Diplome < ApplicationRecord
	belongs_to :demandeur
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/models/formation.rb
class Formation < ApplicationRecord
	belongs_to :demandeur
end

app/models/langue.rb
class Langue < ApplicationRecord
	belongs_to :demandeur
end

app/models/offre.rb
class Offre < ApplicationRecord
end

app/models/pratique.rb
class Pratique < ApplicationRecord
end

app/models/stage.rb
class Stage < ApplicationRecord
	belongs_to :demandeur
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
	before_action :demande_find, only: [:show, :edit, :update, :destroy]

	def liste_demandes
		@demandes = Demande.all
	end

	def new
		@demande = Demande.new

	end

	def create
		@demande = Demande.new(demande_params)
		if @demande.save
			redirect_to @demande
		else 
			render "New"
		end
	end

	def show
		/@demande = Demande.where(demandeur_id: @demande.demandeur_id).take/ 
		/si je décommente cette ligne il me retourne dans le show la première demande qui a été créee/
	end

	def edit
	end

	def destroy
	end

	def update
	end

	private
	def demande_params
		params.require(:demande).permit(:poste_demande, :secteur, :wilaya_demande, :commune_demande, :description, :demandeur_id)
	end

	def demande_find
		@demande = Demande.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demandes_helper.rb
module DemandesHelper
end

app/helpers/demandeurs_helper.rb
module DemandeursHelper
end

app/helpers/diplomes_helper.rb
module DiplomesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/langues_helper.rb
module LanguesHelper
end

app/helpers/offres_helper.rb
module OffresHelper
end

app/helpers/pratiques_helper.rb
module PratiquesHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/demandes/_form_demande_etape4.html.haml
=simple_form_for @demande do |f|
	=f.input :poste_demande, label: "Poste souhaité :"
	%p Secteur 
	=f.select :secteur, [['Informatique', 'Informatique'], ['Banque', 'Banque'], ['Assurances', 'Assurances'], ['reseaux', 'reseaux']]
	%p Wilaya
	=f.select :wilaya_demande, [['Alger', 'Alger'], ['Blida', 'Blida'], ['Tizi ouazzou', 'Tizi ouazzou'], ['Chlef', 'Chlef']]
	%p Commune
	=f.select :commune_demande, [['Alger', 'Alger'], ['Blouizdad', 'Blouizdad'], ['Kouba', 'Kouba'], ['Hydra', 'Hydra']]
	=f.input :description, label: "Description :" 
	
	=f.button :submit, "valider"

app/views/demandes/liste_demandes.html.haml
= link_to "Nouvelle demande", new_demande_path
%h1 les demandes

#jobs

	- @demandes.each do |demande|
		.job
			
				
			%p{:style=>"font-weight:bold; "}= link_to  demande.poste_demande, demande
					
			%p= "Wilaya: " +demande.wilaya_demande.to_s
			%p= "Commune: " +demande.commune_demande.to_s
			%p= "Description: " +demande.description.to_s


			

app/views/demandes/new.html.haml
= link_to "Retour", root_path
%h2 Nouvelle demande

=render "form_demande_etape4"

app/views/demandes/show.html.haml
%h1= @demande.poste_demande
%p= "Secteur: " + @demande.secteur.to_s
%p= "Wilaya: " +@demande.wilaya_demande.to_s
%p= "Commune: " +@demande.commune_demande.to_s
%p= "Description: " +@demande.description.to_s

/%p= @dem.description/
#links
 = link_to "Ajouter une nouvelle demande", "/demandes/new", class: "btn btn-sm btn-default"
 = link_to "Afficher toutes les demandes", "/demandes/liste_demandes", class: "btn btn-sm btn-default"
 /= link_to "Modifier", edit_demande_path(@demande), class: "btn btn-sm btn-default"
 //= link_to "Suprimer", demande_path(@demande), method: :delete, data: { confirm: "are you sure?" }, class: "btn btn-sm btn-default"